### ISSUE TITLE
Cheap verifiability

### ISSUE THREAD

**Issue by burdges** [w3f/messaging#10]
There are "verifiable mixnets" that provide additional assurances of correct node behavior, but historically at enormous performance cost, but approaches improve and @FatemeShirazi knows that literature.

We'll use roughly the Sphinx packet format for numerous reasons, which normally looks nothing like a verifiable mixnet.  We've some ideas though:

In Sphinx, all outgoing packets have a public key of the form either (1) Q=b*P where b=HB(n*P) = HB(p*N) is a blinding factor with P=p*G is an incoming packet's key, N=n*G is the nodes key, or else (2) originate from the node giving them the form Q=q*G with perhaps q=VRF(n,??) in the proof-of-mixing scheme or at least a limited number of such packets. 

We could conceivably produce proofs that "enough" outgoing packets have public keys were reblindings of incoming packets, so part of (1), or perhaps even that all had public keys of form (1) or (2), assuming an [answer to this VRF question](original from the node).  We could not exactly prove that no tampered occurs this way, but if tampering occurs then packets die at the next hop.  I donno if this improves anything since Sphinx ensures that anyways, but sounds worth discussing further, albeit on the side.

As a rule, verifiable mixnets do their mixing in batches, but we envision using Poisson mixing like Loopix, meaning mix delays should be determined by the packet.  We compute the delay by seeding a ChaChaRng with a hash of the key exchange, so HD(n*P)=HD(p*N), and then sampling the delay from this Rng according to an exponential distribution.  An RSA accumulator could likely be used to cheaply prove that outgoing packets correspond to incoming packets, ala zerocoin.  

We'd need to prove the delay was sampled correctly by working in the scalars for some elliptic curve and using Pederson commitments.  In this vein, we only need approximate correctness, so [general sampling methods](https://stats.stackexchange.com/questions/13630/how-to-sample-from-ca-da-1-gammaa/13767#13767) likely apply, but maybe the [quantile function method](https://en.wikipedia.org/wiki/Exponential_distribution#Generating_exponential_variates) gives faster proofs, especially with [arithmetic-geometric mean](https://en.wikipedia.org/wiki/Natural_logarithm#High_precision) method for logarithms, or some method for exponentiation. 

Again, I'm unsure anything here actually buys us anything beyond what Sphinx already buys us, but it's worth understanding the differences.

**Comment by FatemeShirazi** [comment]
Hi Jeff,

I have a question. If we would use source-routing why do we need verifiable
shuffling? As you mentioned, in source-routing if a message is deleted and
replaced by another it would be dropped at the next hop anyway. I think
verifiable shuffle would be used if we need communication/vote integrity
(basically making sure a communication is not dropped, maybe it would be
called availability?) or if we have hop-by-hop routing, no?

Best,
Fatemeh

**Comment by burdges** [comment]
We probably do not :) but I never looked into verifiable shuffles much myself, as they were slow in the past, so I likely do not know all the properties they provide.  I'll look into the [market mixnets](http://fc17.ifca.ai/voting/papers/voting17_prm3.pdf) paper you sent me later today.

**Comment by burdges** [comment]
[Karaoke](https://pdos.csail.mit.edu/papers/karaoke.pdf) nodes publish bloom filters to provide a cheaper proof that servers do not drop cover traffic, thanks @oskarth for mentioning it in #12.  I want relays to share commitments to their replay protection filter anyways, for the probabilistic payment scheme, so idea from Karaoke sounds interesting.  As noted in #13, we should replace bloom filters with cuckoo filters to efficiently track message bodies too.

In Karaoke, there are rounds so servers may observe exact progression for all their cover messages, which sounds unrealistic.  I'm sure doing these checks only sporadically provide far less protection than Karaoke, but presumably it still improves our protections.  We expect enough messages that sharing entire replay protection filters sounds expensive, but the [Fraud Proofs](https://arxiv.org/abs/1809.09044) scheme might help prove that full cuckoo filter exists. 

We could also consider applying ideas from their differential privacy and/or optimistic indistinguishability analysis of Karaoke, but it'd presumably become much harder, due to not operating in round and only checking sporadically.

**Comment by robertkiel** [comment]
closed, ask @burdges
