### ISSUE TITLE
Feed strategies

### ISSUE THREAD

**Issue by burdges** [w3f/messaging#14]
I'll describe some "simple" approaches to doing feeds since @oskarth brought up feeds in https://github.com/w3f/messaging/issues/7#issuecomment-442304463 but warn that I have read a lower proportion of the academic papers that provide "anonymous microblogging" etc., including maybe PIR schemes like [talek](https://github.com/privacylab/talek).

We should assume that _asynchronous feeds may not be, and need not be, that reliable_ because they can inherently pull down an extreme amount of information.  I think this assumption basically kills all schemes in which subscribers track publishers as the publisher frequently moves around some address where they publish.

Instead, a publisher would open a "publisher point" account according to under some update style, which contains either 
 - message body sized "pages" which they periodically replace in full, or else 
 - shorter than message body sized "feed" entries, which can be packed together when sending to users.

Any style might track some metadata like a date.

If online and interested then a subscriber can query such "publisher point" by sending it a rerandomizable authentication token, SURBs, and perhaps some metadata, like a "newer than date".  In this, the "point" only learns the metadata not exactly who queries, so perhaps the metadata could be fuzzed to minimize its knowledge of the number of subscribers.

If a subscriber wants more through updates, even when offline, then they could open both an "aggregation point" and "generator point" accounts and program the "generator point" to supply the "publisher point" with SURBs going to users account on the "aggregation point".  A malicious "generator point" can reveal the subscription, but the "generator point" never changes, so the attack surface is minimal.

**Comment by robertkiel** [comment]
closed, ask @burdges
