### ISSUE TITLE
Current status?

### ISSUE THREAD

**Issue by dumblob** [w3f/messaging#40]
I wonder what is the current status of this effort?

I came here some years ago and since then did not see this moving much. What are the obstackles to move this forward? Is it due to other apps with similar goals (e.g. Briar) becoming stronger and thus there is less market space for a new protocol?

Thanks!

**Comment by burdges** [comment]
I'm too busy with polkadot mostly.  We'll likely write a paper this year.

**Comment by dumblob** [comment]
Looking forward to the paper. Feel free to announce it also in this issue tracker so that subscribers (me inclusive :wink:) get informed. Thanks!
